A = 0
C = 0
G = 0
T = 0
s="GCCGCTCAGTAAATCGGGGTCATAGCCACATGAACCGCGTGAGTTGGTGAAGCTCCCCCAGCTAGTCCAGGACTTTATGCTGAGCTATGGGCTAGTAAAAACACAATCTAGTATGTGCTCACACGCCCCTCACCAACAAGCATCCACGAATTGCGCTCATATAGTCCCTATAGGACCCGTGACGGTGATCTGAACCACTATTGCGTCTTGGTCGGTCGTCGTCTACTTTTAATTTCCTGACTTAAGTTATGAGTAGCTTGTCCATAACGCGTTGGTGATACCACGTAGTCATCCCATTTCAATTGTTAGCGGAACCCCAAGTTATGCAGGGAAGTTAAGACGCACAGGTCGGTCCAGTAATCAATGAAAAATATTCCGTGGAATTTGCAACCTACGTTCATTTACTATATACACCCACATCACTCTATGGACACGGACGTCCTACCACGTTAACCAAAGATTCACGGCAGCAACCCATTTTTTTAACAGACTAGCACCTATTACAGACTTCGGTCACCTTAAATGCCCTCACCTGGAGAAAGCCCTTCGCTGGCATCGTGTTCTAGGGAAGTCCTCGACGGAGCGACTAGAGTAAGTTTATAAGCCGATCCTCCAGGTTGTAATCTTAGGGTACTACACCCGTCCGGCAACCCCCCGACATCTGGGAGAAGTGCGACCTGACGCTGTTTAATGAGTTGCTACGTGATGACCCCCCGCTGCGTTACCTCCGGACTAGATCATCAGGACAATGGGTGTGAACAGCTGTGATGTGAATCGGCACGCTGGTACGAAGCCAGCATCCCTCTAGAGAGAGTCGGGGAAGGTTCTAACTG"
for x in s:
    if x == "A":
        A+=1
    elif x == "C":
        C+=1
    elif x == "G":
        G+=1
    else:
        T+=1

print(A,C,G,T)